CREATE TABLE stdcm_logs (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trace_id VARCHAR(32) UNIQUE NOT NULL,
    request jsonb NOT NULL,
    response jsonb NOT NULL,
	created timestamptz NOT NULL DEFAULT NOW(),
    user_id bigint REFERENCES authn_user ON DELETE CASCADE
);
