-- DO NOT EDIT THIS FILE MANUALLY!

DROP TABLE IF EXISTS "search_scenario";
DROP TRIGGER IF EXISTS search_scenario__ins_trig ON "scenario";
DROP TRIGGER IF EXISTS search_scenario__upd_trig ON "scenario";
DROP FUNCTION IF EXISTS search_scenario__ins_trig_fun;
DROP FUNCTION IF EXISTS search_scenario__upd_trig_fun;
