-- DO NOT EDIT THIS FILE MANUALLY!
-- To change the migration's content, use `editoast search make-migration`.
-- To add custom SQL code, check out `#[derive(Search)]` attributes `prepend_sql` and `append_sql`.

DROP TABLE IF EXISTS "search_scenario";

CREATE TABLE "search_scenario" (
    id BIGINT PRIMARY KEY REFERENCES "scenario"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "name" TEXT,
    "description" TEXT,
    "tags" TEXT,
    "study_id" INTEGER
);

CREATE INDEX "search_scenario_name" ON "search_scenario" USING gin ("name" gin_trgm_ops);
CREATE INDEX "search_scenario_description" ON "search_scenario" USING gin ("description" gin_trgm_ops);
CREATE INDEX "search_scenario_tags" ON "search_scenario" ("tags");
CREATE INDEX "search_scenario_study_id" ON "search_scenario" ("study_id");

CREATE OR REPLACE FUNCTION search_scenario__ins_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO "search_scenario" (id, name, description, tags, study_id)
        SELECT "scenario".id AS id, osrd_prepare_for_search(scenario.name) AS name,
    osrd_prepare_for_search(scenario.description) AS description,
    (osrd_prepare_for_search_tags(scenario.tags)) AS tags,
    (scenario.study_id) AS study_id
        FROM (SELECT NEW.*) AS "scenario"
        ;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_scenario__ins_trig
AFTER INSERT ON "scenario"
FOR EACH ROW EXECUTE FUNCTION search_scenario__ins_trig_fun();


CREATE OR REPLACE FUNCTION search_scenario__upd_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE "search_scenario"
        SET "name" = osrd_prepare_for_search(scenario.name),
        "description" = osrd_prepare_for_search(scenario.description),
        "tags" = (osrd_prepare_for_search_tags(scenario.tags)),
        "study_id" = (scenario.study_id)
        FROM (SELECT NEW.*) AS "scenario"
        
        WHERE "scenario".id = "search_scenario".id;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_scenario__upd_trig
AFTER UPDATE ON "scenario"
FOR EACH ROW EXECUTE FUNCTION search_scenario__upd_trig_fun();



INSERT INTO "search_scenario" (id, "name", "description", "tags", "study_id")
SELECT
    "scenario"."id" AS id,
    osrd_prepare_for_search(scenario.name) AS name
,    osrd_prepare_for_search(scenario.description) AS description
,    (osrd_prepare_for_search_tags(scenario.tags)) AS tags
,    (scenario.study_id) AS study_id
FROM "scenario"
    ;
